### ISSUE TITLE
insecurely downloading shell scripts

### ISSUE THREAD

**Issue by lucasduffey** [nongiach/arm_now#1]
```

install_opkg = {
        "armv5-eabi":"""wget -O - http://pkg.entware.net/binaries/armv5/installer/entware_install.sh | /bin/sh""",
        "armv7-eabihf":"""wget -O - http://pkg.entware.net/binaries/armv5/installer/entware_install.sh | /bin/sh""",
        "mips32el":"""wget -O - http://pkg.entware.net/binaries/mipsel/installer/installer.sh | /bin/sh""",
        "x86-64-core-i7":"""wget -O - http://pkg.entware.net/binaries/x86-64/installer/entware_install.sh | /bin/sh""",
        "x86-core2":"""wget -O - http://pkg.entware.net/binaries/x86-32/installer/entware_install.sh | /bin/sh""",
        "x86-i686":"""wget -O - http://pkg.entware.net/binaries/x86-32/installer/entware_install.sh | /bin/sh""",
}
```

**Comment by nongiach** [comment]
hey, I will fix this as soon as I can, ssl isn't configured on the vm and thoose script are only run inside the vm. For the quick fix I will download them with https from the host and pass the script to the guest. Thx.

**Comment by nongiach** [comment]
Hey,
This issue is now corrected on the dev branch, thx :)
It was not that easy because by default the images I was using don't support https, but now they do.
I preconfigured them, I could go further and compile my own images from scratch but it's time-consuming.
![image](https://user-images.githubusercontent.com/5711608/40944126-e989607c-6853-11e8-8784-9fea090e6530.png)

**Comment by nongiach** [comment]
Hey,
I pushed on master, I'm closing this issue.
Your name is now mentioned here => https://github.com/nongiach/arm_now/wiki/4.1-Q&A-and-incoming-features

Thx
